/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMoonpageCollection__factory } from "./IMoonpageCollection__factory";
export { IMoonpageManager__factory } from "./IMoonpageManager__factory";
