/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMoonpageCollection } from "./IMoonpageCollection";
export type { IMoonpageManager } from "./IMoonpageManager";
